version: "3.7"

services:
    runner:
      image: tcardonne/github-runner:ubuntu-20.04
      container_name: runner-self-hosted
      privileged: true
      environment:
        RUNNER_NAME: "my-runner"
        RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
        #RUNNER_ORGANIZATION_URL: ${RUNNER_ORGANIZATION_URL}
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sockz
        #- ./.pio:/home/runner/_work/pipeline-esp32/pipeline-esp32/.pio
        #- persistent:/home/runner/_work/pipeline-esp32/pipeline-esp32/.pio
        #- persistent:/opt/hostedtoolcache
      devices:
        - '/dev/ttyUSB0:/dev/ttyUSB0'